# Site settings
title: Digitally Demused
description: "A blog for tech updates and dank memes."
url: "https://shabab477.github.io/"
author:
  name: "Shabab Karim"
  email: "shababkarim93@gmail.com"
  url: "https://www.facebook.com/shabab477"
facebook:
  app_id: 1204558196300544
  

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: true
